version: "3"

services:
  transaction_service:
    image: ghcr.io/etherdata-blockchain/etdstats/transaction_service:1.13.4
    build:
      context: .
      dockerfile: docker/services/service.dockerfile
      args:
        - APP_NAME=transaction_service
    container_name: transaction_service
    ports:
      - "8080:8080"
    environment:
      - RPC_URL=${RPC_URL}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
  contract_service:
    image: ghcr.io/etherdata-blockchain/etdstats/contract_service:1.13.4
    build:
      context: .
      dockerfile: docker/services/service.dockerfile
      args:
        - APP_NAME=contract_service
    container_name: contract_service
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis-data:/data
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017