version: "3"

services:
  transaction_service:
    image: ghcr.io/etherdata-blockchain/etdstats/transaction_service:0.16.0
    build:
      context: .
      dockerfile: docker/services/service.dockerfile
      args:
        - APP_NAME=transaction_service
    container_name: transaction_service
    ports:
      - "8080:8080"
    environment:
      - RPC_URL=${RPC_URL}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis-data:/data