openapi: "3.0.0"
info:
  description: "This belongs part of ETDStats microservices which will provide a transaction and block services"
  version: "1.0.0"
  title: "Transaction service"
  termsOfService: "https://github.com/etherdata-blockchain"


tags:
  - name: "transaction"
    description: "Get blocks and transactions details"
  - name: "health"
    description: "Get server's health info"

servers:
  - url: stats.etdchain.net/v3/transaction
    description: Production server
  - url: stats.debugchain.net/v3/transaction
    description: Testing server

paths:
  /health:
    get:
      tags:
        - "health"
      summary: "Get server's health info"
      description: "Will return a error reason if not healthy"
      responses:
        "200":
          description: "Server is up"
        "500":
          description: "Server is down"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
components:
  schemas:
    error:
      type: object
      required: ["reason"]
      properties:
        relatedServices:
          type: string

