openapi: "3.0.0"
info:
  description: "This belongs part of ETDStats microservices which will provide a node service. Pending!"
  version: "1.0.0"
  title: "Node service"
  termsOfService: "https://github.com/etherdata-blockchain"


tags:
  - name: "node"
    description: "Get blocks and transactions details"
  - name: "health"
    description: "Get server's health info"

servers:
  - url: https://api.etdchain.net/stats/node
    description: Production server
  - url: https://api.debugchain.net/stats/node
    description: Testing server

paths:
  /info:
    post:
      tags:
        - "node"
      summary: "Submit latest block info"
      responses:
        "200":
          description: "OK"
  /login:
    post:
      tags:
        - node
      summary: Log in
      responses:
        201:
          description: "OK"

  /health:
    get:
      tags:
        - "health"
      summary: "Get server's health info"
      description: "Will return a error reason if not healthy"
      responses:
        "200":
          description: "Server is up"
          content:
            application/json:
              schema:
                $ref: "health_service.spec.yaml#/components/schemas/error"
        "500":
          description: "Server is down"
          content:
            application/json:
              schema:
                $ref: "health_service.spec.yaml#/components/schemas/error"
components:
  schemas:
    node-info:
      type: object