name: Deploy to Cloud Run

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:  ["contract_service"]
    steps:
      - uses: actions/checkout@v2
      - name: Login to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker --quiet
      - name: Pull image from GCR
        run:  docker pull ghcr.io/${{ github.repository }}/${{ matrix.app }}:${{ github.event.inputs.tag }}
      - name: Tag image for GCR
        run: docker tag ghcr.io/${{ github.repository }}/${{ matrix.app }}:${{ github.event.inputs.tag }} gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ matrix.app }}:${{ github.event.inputs.tag }}
      - uses: frabert/replace-string-action@v2.0
        id: runner
        with:
          pattern: '_'
          string: ${{matrix.app}}
          replace-with: '-'
          flags: "g"
      - name: Deploy cloud run
        run: gcloud run deploy ${{steps.runner.outputs.replaced}} --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ matrix.app }}:${{ github.event.inputs.tag }} --region asia-southeast1 --platform managed --set-env-vars=DATABASE_URL=${{secrets.DATABASE_TEST_URL}},JWT_SECRET=${{secrets.JWT_SECRET}}

