name: e2e Testing
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  pull_request:

jobs:
  e2e:
    name: e2e Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.5
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
      - run: pnpm install
      - name: Install Playwright
        run: npx playwright install --with-deps
      - run: pnpm e2e
        env:
          TEST_URL: "https://stats.etdchain.net"